language: php

env:
 - APP_KEY=base64:JjrFWC+TGnySY2LsldPXAxuHpyjh8UuoPMt6yy2gJ8U=
 - CASTLE_SECRET=tYiqkpSVgMHSZpwSJTsBipyaS1zxMCsW

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: phpunit
